/**
 * Mock data for Q10 Genius — Demo Mode
 *
 * Realistic data for a Central American language school in Guatemala.
 * All names, phones (+502), documents (DPI), and amounts (Quetzales)
 * are consistent with the Guatemalan context.
 */

// ─── Catalogs ───

const programas = [
  {
    Codigo: 'PROG-001',
    Id: 'PROG-001',
    Nombre: 'Inglés Básico (A1-A2)',
    Descripcion: 'Curso de inglés para principiantes — niveles A1 y A2 del MCER',
    Duracion: '6 meses',
    Estado: 'Activo',
  },
  {
    Codigo: 'PROG-002',
    Id: 'PROG-002',
    Nombre: 'Inglés Intermedio (B1)',
    Descripcion: 'Curso de inglés intermedio — nivel B1 del MCER',
    Duracion: '6 meses',
    Estado: 'Activo',
  },
  {
    Codigo: 'PROG-003',
    Id: 'PROG-003',
    Nombre: 'Inglés Avanzado (B2-C1)',
    Descripcion: 'Curso de inglés avanzado — niveles B2 y C1 del MCER',
    Duracion: '6 meses',
    Estado: 'Activo',
  },
  {
    Codigo: 'PROG-004',
    Id: 'PROG-004',
    Nombre: 'Inglés para Negocios',
    Descripcion: 'Business English — comunicación profesional y corporativa',
    Duracion: '4 meses',
    Estado: 'Activo',
  },
  {
    Codigo: 'PROG-005',
    Id: 'PROG-005',
    Nombre: 'Francés Básico',
    Descripcion: 'Introducción al idioma francés — niveles A1 y A2',
    Duracion: '6 meses',
    Estado: 'Activo',
  },
  {
    Codigo: 'PROG-006',
    Id: 'PROG-006',
    Nombre: 'Preparación TOEFL',
    Descripcion: 'Curso intensivo de preparación para el examen TOEFL iBT',
    Duracion: '3 meses',
    Estado: 'Activo',
  },
];

const periodos = [
  {
    Codigo: 'PER-2026-I',
    Id: 'PER-2026-I',
    Nombre: '2026-I (Enero - Junio)',
    Descripcion: 'Primer semestre 2026',
    Fecha_inicio: '2026-01-12',
    Fecha_fin: '2026-06-27',
    Estado: 'Activo',
  },
  {
    Codigo: 'PER-2026-II',
    Id: 'PER-2026-II',
    Nombre: '2026-II (Julio - Diciembre)',
    Descripcion: 'Segundo semestre 2026',
    Fecha_inicio: '2026-07-06',
    Fecha_fin: '2026-12-12',
    Estado: 'Activo',
  },
  {
    Codigo: 'PER-INT-MAR26',
    Id: 'PER-INT-MAR26',
    Nombre: 'Intensivo Marzo 2026',
    Descripcion: 'Curso intensivo de marzo — 4 semanas',
    Fecha_inicio: '2026-03-02',
    Fecha_fin: '2026-03-28',
    Estado: 'Activo',
  },
  {
    Codigo: 'PER-INT-AGO26',
    Id: 'PER-INT-AGO26',
    Nombre: 'Intensivo Agosto 2026',
    Descripcion: 'Curso intensivo de agosto — 4 semanas',
    Fecha_inicio: '2026-08-03',
    Fecha_fin: '2026-08-29',
    Estado: 'Activo',
  },
];

const sedes = [
  {
    Codigo: 'SEDE-CENTRAL',
    Id: 'SEDE-CENTRAL',
    Nombre: 'Sede Central (Ciudad de Guatemala)',
    Direccion: '6a Avenida 9-45, Zona 1, Ciudad de Guatemala',
    Telefono: '+502 2220-1500',
    Estado: 'Activo',
  },
  {
    Codigo: 'SEDE-Z10',
    Id: 'SEDE-Z10',
    Nombre: 'Sede Zona 10',
    Direccion: '13 Calle 2-60, Zona 10, Ciudad de Guatemala',
    Telefono: '+502 2363-2800',
    Estado: 'Activo',
  },
  {
    Codigo: 'SEDE-ANTIGUA',
    Id: 'SEDE-ANTIGUA',
    Nombre: 'Sede Antigua Guatemala',
    Direccion: '5a Avenida Norte #33, Antigua Guatemala, Sacatepéquez',
    Telefono: '+502 7832-4100',
    Estado: 'Activo',
  },
];

// ─── Contacts / Students ───

const contactos = [
  {
    Codigo_contacto: 'CON-001',
    Codigo: 'CON-001',
    Id: 'CON-001',
    Nombres: 'María Fernanda',
    Apellidos: 'López Castillo',
    Correo_electronico: 'maria.lopez@gmail.com',
    Telefono: '+502 4512-3489',
    Celular: '+502 4512-3489',
    Tipo_documento: 'DPI',
    Numero_documento: '2456 78901 0101',
    Nacionalidad: 'Guatemalteca',
    Fecha_creacion: '2025-11-15',
  },
  {
    Codigo_contacto: 'CON-002',
    Codigo: 'CON-002',
    Id: 'CON-002',
    Nombres: 'Carlos Alberto',
    Apellidos: 'García Morales',
    Correo_electronico: 'carlos.garcia@hotmail.com',
    Telefono: '+502 5578-6234',
    Celular: '+502 5578-6234',
    Tipo_documento: 'DPI',
    Numero_documento: '1987 65432 0108',
    Nacionalidad: 'Guatemalteco',
    Fecha_creacion: '2025-12-03',
  },
  {
    Codigo_contacto: 'CON-003',
    Codigo: 'CON-003',
    Id: 'CON-003',
    Nombres: 'Ana Lucía',
    Apellidos: 'Hernández Paz',
    Correo_electronico: 'ana.hernandez@yahoo.com',
    Telefono: '+502 3301-7845',
    Celular: '+502 3301-7845',
    Tipo_documento: 'DPI',
    Numero_documento: '3012 45678 0301',
    Nacionalidad: 'Guatemalteca',
    Fecha_creacion: '2026-01-10',
  },
  {
    Codigo_contacto: 'CON-004',
    Codigo: 'CON-004',
    Id: 'CON-004',
    Nombres: 'José Miguel',
    Apellidos: 'Ramírez Solís',
    Correo_electronico: 'jose.ramirez@outlook.com',
    Telefono: '+502 4123-9087',
    Celular: '+502 4123-9087',
    Tipo_documento: 'DPI',
    Numero_documento: '2678 90123 0501',
    Nacionalidad: 'Guatemalteco',
    Fecha_creacion: '2026-01-22',
  },
  {
    Codigo_contacto: 'CON-005',
    Codigo: 'CON-005',
    Id: 'CON-005',
    Nombres: 'Sofía Alejandra',
    Apellidos: 'Mendoza Vásquez',
    Correo_electronico: 'sofia.mendoza@gmail.com',
    Telefono: '+502 5234-1678',
    Celular: '+502 5234-1678',
    Tipo_documento: 'DPI',
    Numero_documento: '1845 23456 0901',
    Nacionalidad: 'Guatemalteca',
    Fecha_creacion: '2026-02-05',
  },
  {
    Codigo_contacto: 'CON-006',
    Codigo: 'CON-006',
    Id: 'CON-006',
    Nombres: 'Diego Fernando',
    Apellidos: 'Pineda Álvarez',
    Correo_electronico: 'diego.pineda@gmail.com',
    Telefono: '+502 4789-3456',
    Celular: '+502 4789-3456',
    Tipo_documento: 'DPI',
    Numero_documento: '2901 67890 1201',
    Nacionalidad: 'Guatemalteco',
    Fecha_creacion: '2026-02-18',
  },
  {
    Codigo_contacto: 'CON-007',
    Codigo: 'CON-007',
    Id: 'CON-007',
    Nombres: 'Valentina',
    Apellidos: 'Cruz Figueroa',
    Correo_electronico: 'valentina.cruz@hotmail.com',
    Telefono: '+502 3567-2190',
    Celular: '+502 3567-2190',
    Tipo_documento: 'DPI',
    Numero_documento: '3234 56789 0701',
    Nacionalidad: 'Guatemalteca',
    Fecha_creacion: '2026-03-01',
  },
];

const estudiantes = [
  {
    Codigo_estudiante: 'EST-001',
    Codigo: 'EST-001',
    Id: 'EST-001',
    Nombres: 'María Fernanda',
    Apellidos: 'López Castillo',
    Correo_electronico: 'maria.lopez@gmail.com',
    Telefono: '+502 4512-3489',
    Celular: '+502 4512-3489',
    Tipo_documento: 'DPI',
    Numero_documento: '2456 78901 0101',
    Nacionalidad: 'Guatemalteca',
    Fecha_nacimiento: '1998-04-12',
    Genero: 'Femenino',
    Codigo_contacto: 'CON-001',
    Codigo_programa: 'PROG-002',
    Codigo_periodo: 'PER-2026-I',
    Codigo_sede: 'SEDE-CENTRAL',
    Estado: 'Activo',
  },
  {
    Codigo_estudiante: 'EST-002',
    Codigo: 'EST-002',
    Id: 'EST-002',
    Nombres: 'Carlos Alberto',
    Apellidos: 'García Morales',
    Correo_electronico: 'carlos.garcia@hotmail.com',
    Telefono: '+502 5578-6234',
    Celular: '+502 5578-6234',
    Tipo_documento: 'DPI',
    Numero_documento: '1987 65432 0108',
    Nacionalidad: 'Guatemalteco',
    Fecha_nacimiento: '1995-08-23',
    Genero: 'Masculino',
    Codigo_contacto: 'CON-002',
    Codigo_programa: 'PROG-004',
    Codigo_periodo: 'PER-2026-I',
    Codigo_sede: 'SEDE-Z10',
    Estado: 'Activo',
  },
  {
    Codigo_estudiante: 'EST-003',
    Codigo: 'EST-003',
    Id: 'EST-003',
    Nombres: 'Ana Lucía',
    Apellidos: 'Hernández Paz',
    Correo_electronico: 'ana.hernandez@yahoo.com',
    Telefono: '+502 3301-7845',
    Celular: '+502 3301-7845',
    Tipo_documento: 'DPI',
    Numero_documento: '3012 45678 0301',
    Nacionalidad: 'Guatemalteca',
    Fecha_nacimiento: '2000-11-05',
    Genero: 'Femenino',
    Codigo_contacto: 'CON-003',
    Codigo_programa: 'PROG-001',
    Codigo_periodo: 'PER-2026-I',
    Codigo_sede: 'SEDE-ANTIGUA',
    Estado: 'Activo',
  },
  {
    Codigo_estudiante: 'EST-004',
    Codigo: 'EST-004',
    Id: 'EST-004',
    Nombres: 'José Miguel',
    Apellidos: 'Ramírez Solís',
    Correo_electronico: 'jose.ramirez@outlook.com',
    Telefono: '+502 4123-9087',
    Celular: '+502 4123-9087',
    Tipo_documento: 'DPI',
    Numero_documento: '2678 90123 0501',
    Nacionalidad: 'Guatemalteco',
    Fecha_nacimiento: '1997-02-14',
    Genero: 'Masculino',
    Codigo_contacto: 'CON-004',
    Codigo_programa: 'PROG-006',
    Codigo_periodo: 'PER-INT-MAR26',
    Codigo_sede: 'SEDE-CENTRAL',
    Estado: 'Activo',
  },
  {
    Codigo_estudiante: 'EST-005',
    Codigo: 'EST-005',
    Id: 'EST-005',
    Nombres: 'Sofía Alejandra',
    Apellidos: 'Mendoza Vásquez',
    Correo_electronico: 'sofia.mendoza@gmail.com',
    Telefono: '+502 5234-1678',
    Celular: '+502 5234-1678',
    Tipo_documento: 'DPI',
    Numero_documento: '1845 23456 0901',
    Nacionalidad: 'Guatemalteca',
    Fecha_nacimiento: '1999-07-30',
    Genero: 'Femenino',
    Codigo_contacto: 'CON-005',
    Codigo_programa: 'PROG-003',
    Codigo_periodo: 'PER-2026-I',
    Codigo_sede: 'SEDE-Z10',
    Estado: 'Activo',
  },
];

// ─── Opportunities ───

const oportunidades = [
  {
    Codigo: 'OPP-001',
    Id: 'OPP-001',
    Nombres: 'Roberto Alejandro',
    Apellidos: 'Estrada Monzón',
    Correo_electronico: 'roberto.estrada@gmail.com',
    Telefono: '+502 4890-1234',
    Celular: '+502 4890-1234',
    Tipo_documento: 'DPI',
    Numero_documento: '1567 89012 0401',
    Estado: 'Nueva',
    Origen: 'WhatsApp',
    Programa_interes: 'Inglés Básico (A1-A2)',
    Observaciones: 'Interesado en clases sabatinas, consulta por horarios',
    Fecha_creacion: '2026-03-18',
  },
  {
    Codigo: 'OPP-002',
    Id: 'OPP-002',
    Nombres: 'Gabriela',
    Apellidos: 'Mejía Santos',
    Correo_electronico: 'gabriela.mejia@yahoo.com',
    Telefono: '+502 5612-7890',
    Celular: '+502 5612-7890',
    Tipo_documento: 'DPI',
    Numero_documento: '2345 67890 0601',
    Estado: 'En seguimiento',
    Origen: 'Referido',
    Programa_interes: 'Inglés para Negocios',
    Observaciones: 'Referida por María Fernanda López. Trabaja en exportadora, necesita inglés corporativo.',
    Fecha_creacion: '2026-03-10',
  },
  {
    Codigo: 'OPP-003',
    Id: 'OPP-003',
    Nombres: 'Luis Pedro',
    Apellidos: 'Barrios Cifuentes',
    Correo_electronico: 'luis.barrios@hotmail.com',
    Telefono: '+502 3456-7812',
    Celular: '+502 3456-7812',
    Tipo_documento: 'DPI',
    Numero_documento: '1890 12345 1001',
    Estado: 'Contactado',
    Origen: 'Redes sociales',
    Programa_interes: 'Preparación TOEFL',
    Observaciones: 'Planea aplicar a maestría en EE.UU., necesita TOEFL 90+',
    Fecha_creacion: '2026-03-05',
  },
  {
    Codigo: 'OPP-004',
    Id: 'OPP-004',
    Nombres: 'Andrea Paola',
    Apellidos: 'Juárez Cano',
    Correo_electronico: 'andrea.juarez@gmail.com',
    Telefono: '+502 4234-5678',
    Celular: '+502 4234-5678',
    Tipo_documento: 'DPI',
    Numero_documento: '3456 78901 0201',
    Estado: 'Inscrita',
    Origen: 'Página web',
    Programa_interes: 'Francés Básico',
    Observaciones: 'Ya completó inscripción para el período 2026-I',
    Fecha_creacion: '2026-02-20',
  },
];

// ─── Financial ───

const ordenesDePago = [
  {
    Codigo_orden: 'ORD-001',
    Codigo: 'ORD-001',
    Id: 'ORD-001',
    Codigo_estudiante: 'EST-001',
    Codigo_matricula: 'MAT-001',
    Concepto_pago: 'Matrícula — Inglés Intermedio (B1)',
    Valor: 1200,
    Moneda: 'GTQ',
    Estado: 'Pagado',
    Fecha_creacion: '2026-01-08',
    Fecha_vencimiento: '2026-01-20',
    Fecha_pago: '2026-01-15',
  },
  {
    Codigo_orden: 'ORD-002',
    Codigo: 'ORD-002',
    Id: 'ORD-002',
    Codigo_estudiante: 'EST-002',
    Codigo_matricula: 'MAT-002',
    Concepto_pago: 'Matrícula — Inglés para Negocios',
    Valor: 1800,
    Moneda: 'GTQ',
    Estado: 'Pagado',
    Fecha_creacion: '2026-01-10',
    Fecha_vencimiento: '2026-01-25',
    Fecha_pago: '2026-01-20',
  },
  {
    Codigo_orden: 'ORD-003',
    Codigo: 'ORD-003',
    Id: 'ORD-003',
    Codigo_estudiante: 'EST-003',
    Codigo_matricula: 'MAT-003',
    Concepto_pago: 'Matrícula — Inglés Básico (A1-A2)',
    Valor: 950,
    Moneda: 'GTQ',
    Estado: 'Pendiente',
    Fecha_creacion: '2026-03-01',
    Fecha_vencimiento: '2026-03-15',
    Fecha_pago: null,
  },
  {
    Codigo_orden: 'ORD-004',
    Codigo: 'ORD-004',
    Id: 'ORD-004',
    Codigo_estudiante: 'EST-004',
    Codigo_matricula: 'MAT-004',
    Concepto_pago: 'Curso Intensivo — Preparación TOEFL',
    Valor: 2000,
    Moneda: 'GTQ',
    Estado: 'Pendiente',
    Fecha_creacion: '2026-03-10',
    Fecha_vencimiento: '2026-03-25',
    Fecha_pago: null,
  },
  {
    Codigo_orden: 'ORD-005',
    Codigo: 'ORD-005',
    Id: 'ORD-005',
    Codigo_estudiante: 'EST-005',
    Codigo_matricula: 'MAT-005',
    Concepto_pago: 'Matrícula — Inglés Avanzado (B2-C1)',
    Valor: 1500,
    Moneda: 'GTQ',
    Estado: 'Pagado',
    Fecha_creacion: '2026-01-12',
    Fecha_vencimiento: '2026-01-30',
    Fecha_pago: '2026-01-28',
  },
];

const conceptosDePago = [
  { Codigo: 'CPAGO-001', Nombre: 'Matrícula', Valor_defecto: 1200 },
  { Codigo: 'CPAGO-002', Nombre: 'Mensualidad', Valor_defecto: 500 },
  { Codigo: 'CPAGO-003', Nombre: 'Material didáctico', Valor_defecto: 350 },
  { Codigo: 'CPAGO-004', Nombre: 'Examen de ubicación', Valor_defecto: 150 },
  { Codigo: 'CPAGO-005', Nombre: 'Certificación', Valor_defecto: 750 },
  { Codigo: 'CPAGO-006', Nombre: 'Curso intensivo', Valor_defecto: 2000 },
];

// ─── Matriculas ───

const matriculas = [
  {
    Codigo_matricula: 'MAT-001',
    Codigo: 'MAT-001',
    Id: 'MAT-001',
    Codigo_estudiante: 'EST-001',
    Codigo_programa: 'PROG-002',
    Codigo_periodo: 'PER-2026-I',
    Codigo_sede: 'SEDE-CENTRAL',
    Codigo_inscripcion: 'INS-001',
    Estado: 'Activa',
    Fecha_creacion: '2026-01-08',
  },
  {
    Codigo_matricula: 'MAT-002',
    Codigo: 'MAT-002',
    Id: 'MAT-002',
    Codigo_estudiante: 'EST-002',
    Codigo_programa: 'PROG-004',
    Codigo_periodo: 'PER-2026-I',
    Codigo_sede: 'SEDE-Z10',
    Codigo_inscripcion: 'INS-002',
    Estado: 'Activa',
    Fecha_creacion: '2026-01-10',
  },
  {
    Codigo_matricula: 'MAT-003',
    Codigo: 'MAT-003',
    Id: 'MAT-003',
    Codigo_estudiante: 'EST-003',
    Codigo_programa: 'PROG-001',
    Codigo_periodo: 'PER-2026-I',
    Codigo_sede: 'SEDE-ANTIGUA',
    Codigo_inscripcion: 'INS-003',
    Estado: 'Pendiente pago',
    Fecha_creacion: '2026-03-01',
  },
];

// ─── Inscripciones ───

const inscripciones = [
  {
    Codigo_inscripcion: 'INS-001',
    Codigo: 'INS-001',
    Id: 'INS-001',
    Codigo_estudiante: 'EST-001',
    Codigo_programa: 'PROG-002',
    Codigo_periodo: 'PER-2026-I',
    Codigo_sede: 'SEDE-CENTRAL',
    Estado: 'Confirmada',
    Fecha_creacion: '2026-01-08',
  },
  {
    Codigo_inscripcion: 'INS-002',
    Codigo: 'INS-002',
    Id: 'INS-002',
    Codigo_estudiante: 'EST-002',
    Codigo_programa: 'PROG-004',
    Codigo_periodo: 'PER-2026-I',
    Codigo_sede: 'SEDE-Z10',
    Estado: 'Confirmada',
    Fecha_creacion: '2026-01-10',
  },
  {
    Codigo_inscripcion: 'INS-003',
    Codigo: 'INS-003',
    Id: 'INS-003',
    Codigo_estudiante: 'EST-003',
    Codigo_programa: 'PROG-001',
    Codigo_periodo: 'PER-2026-I',
    Codigo_sede: 'SEDE-ANTIGUA',
    Estado: 'Pendiente',
    Fecha_creacion: '2026-03-01',
  },
];

// ─── Account Balances (Estado de Cuenta Estudiantes) ───

const estadocuentaestudiantes = [
  {
    Codigo_estudiante: 'EST-001',
    Nombres: 'María Fernanda',
    Apellidos: 'López Castillo',
    Saldo: 1500,
    Total_pagado: 3500,
    Total_deuda: 5000,
    Moneda: 'GTQ',
  },
  {
    Codigo_estudiante: 'EST-002',
    Nombres: 'Carlos Alberto',
    Apellidos: 'García Morales',
    Saldo: 0,
    Total_pagado: 5400,
    Total_deuda: 5400,
    Moneda: 'GTQ',
  },
  {
    Codigo_estudiante: 'EST-003',
    Nombres: 'Ana Lucía',
    Apellidos: 'Hernández Paz',
    Saldo: 2850,
    Total_pagado: 950,
    Total_deuda: 3800,
    Moneda: 'GTQ',
  },
  {
    Codigo_estudiante: 'EST-004',
    Nombres: 'José Miguel',
    Apellidos: 'Ramírez Solís',
    Saldo: 2000,
    Total_pagado: 0,
    Total_deuda: 2000,
    Moneda: 'GTQ',
  },
  {
    Codigo_estudiante: 'EST-005',
    Nombres: 'Sofía Alejandra',
    Apellidos: 'Mendoza Vásquez',
    Saldo: 750,
    Total_pagado: 4500,
    Total_deuda: 5250,
    Moneda: 'GTQ',
  },
];

// ─── Pending Payments ───

const pagosPendientes = [
  {
    Codigo: 'PP-001',
    Codigo_estudiante: 'EST-001',
    Nombres: 'María Fernanda',
    Apellidos: 'López Castillo',
    Concepto: 'Mensualidad Marzo 2026',
    Valor: 750,
    Moneda: 'GTQ',
    Fecha_vencimiento: '2026-03-31',
    Estado: 'Pendiente',
  },
  {
    Codigo: 'PP-002',
    Codigo_estudiante: 'EST-003',
    Nombres: 'Ana Lucía',
    Apellidos: 'Hernández Paz',
    Concepto: 'Matrícula — Inglés Básico (A1-A2)',
    Valor: 950,
    Moneda: 'GTQ',
    Fecha_vencimiento: '2026-03-15',
    Estado: 'Pendiente',
  },
  {
    Codigo: 'PP-003',
    Codigo_estudiante: 'EST-004',
    Nombres: 'José Miguel',
    Apellidos: 'Ramírez Solís',
    Concepto: 'Curso Intensivo — Preparación TOEFL',
    Valor: 2000,
    Moneda: 'GTQ',
    Fecha_vencimiento: '2026-03-25',
    Estado: 'Pendiente',
  },
  {
    Codigo: 'PP-004',
    Codigo_estudiante: 'EST-005',
    Nombres: 'Sofía Alejandra',
    Apellidos: 'Mendoza Vásquez',
    Concepto: 'Mensualidad Marzo 2026',
    Valor: 750,
    Moneda: 'GTQ',
    Fecha_vencimiento: '2026-03-31',
    Estado: 'Pendiente',
  },
];

// ─── Completed Payments ───

const pagos = [
  {
    Codigo: 'PAG-001',
    Codigo_estudiante: 'EST-001',
    Nombres: 'María Fernanda',
    Apellidos: 'López Castillo',
    Concepto: 'Matrícula — Inglés Intermedio (B1)',
    Valor: 1200,
    Moneda: 'GTQ',
    Fecha_pago: '2026-01-15',
    Estado: 'Pagado',
    Metodo_pago: 'Transferencia bancaria',
  },
  {
    Codigo: 'PAG-002',
    Codigo_estudiante: 'EST-001',
    Nombres: 'María Fernanda',
    Apellidos: 'López Castillo',
    Concepto: 'Mensualidad Enero 2026',
    Valor: 750,
    Moneda: 'GTQ',
    Fecha_pago: '2026-01-15',
    Estado: 'Pagado',
    Metodo_pago: 'Transferencia bancaria',
  },
  {
    Codigo: 'PAG-003',
    Codigo_estudiante: 'EST-001',
    Nombres: 'María Fernanda',
    Apellidos: 'López Castillo',
    Concepto: 'Mensualidad Febrero 2026',
    Valor: 750,
    Moneda: 'GTQ',
    Fecha_pago: '2026-02-14',
    Estado: 'Pagado',
    Metodo_pago: 'Efectivo',
  },
  {
    Codigo: 'PAG-004',
    Codigo_estudiante: 'EST-002',
    Nombres: 'Carlos Alberto',
    Apellidos: 'García Morales',
    Concepto: 'Matrícula — Inglés para Negocios',
    Valor: 1800,
    Moneda: 'GTQ',
    Fecha_pago: '2026-01-20',
    Estado: 'Pagado',
    Metodo_pago: 'Tarjeta de crédito',
  },
  {
    Codigo: 'PAG-005',
    Codigo_estudiante: 'EST-002',
    Nombres: 'Carlos Alberto',
    Apellidos: 'García Morales',
    Concepto: 'Mensualidad Febrero 2026',
    Valor: 1800,
    Moneda: 'GTQ',
    Fecha_pago: '2026-02-18',
    Estado: 'Pagado',
    Metodo_pago: 'Transferencia bancaria',
  },
  {
    Codigo: 'PAG-006',
    Codigo_estudiante: 'EST-005',
    Nombres: 'Sofía Alejandra',
    Apellidos: 'Mendoza Vásquez',
    Concepto: 'Matrícula — Inglés Avanzado (B2-C1)',
    Valor: 1500,
    Moneda: 'GTQ',
    Fecha_pago: '2026-01-28',
    Estado: 'Pagado',
    Metodo_pago: 'Depósito bancario',
  },
];

// ─── Deals / Business Opportunities ───

const negocios = [
  {
    Codigo: 'NEG-001',
    Id: 'NEG-001',
    Codigo_oportunidad: 'OPP-001',
    Nombre: 'Matrícula Inglés Básico — Roberto Estrada',
    Valor: 2500,
    Moneda: 'GTQ',
    Estado: 'En progreso',
    Etapa: 'Propuesta enviada',
    Fecha_creacion: '2026-03-18',
    Fecha_cierre_estimada: '2026-04-01',
  },
  {
    Codigo: 'NEG-002',
    Id: 'NEG-002',
    Codigo_oportunidad: 'OPP-002',
    Nombre: 'Business English — Gabriela Mejía',
    Valor: 5400,
    Moneda: 'GTQ',
    Estado: 'En progreso',
    Etapa: 'Negociación',
    Fecha_creacion: '2026-03-10',
    Fecha_cierre_estimada: '2026-03-28',
  },
  {
    Codigo: 'NEG-003',
    Id: 'NEG-003',
    Codigo_oportunidad: 'OPP-003',
    Nombre: 'TOEFL Prep — Luis Pedro Barrios',
    Valor: 3500,
    Moneda: 'GTQ',
    Estado: 'En progreso',
    Etapa: 'Contacto inicial',
    Fecha_creacion: '2026-03-05',
    Fecha_cierre_estimada: '2026-04-15',
  },
];

// ─── Activities / Tasks per Opportunity ───

const actividades = [
  {
    Codigo: 'ACT-001',
    Id: 'ACT-001',
    Codigo_oportunidad: 'OPP-001',
    Tipo: 'Llamada',
    Descripcion: 'Seguimiento interés programa Inglés Básico',
    Fecha: '2026-03-20',
    Estado: 'Completada',
    Responsable: 'Admin',
  },
  {
    Codigo: 'ACT-002',
    Id: 'ACT-002',
    Codigo_oportunidad: 'OPP-001',
    Tipo: 'WhatsApp',
    Descripcion: 'Envío de brochure y horarios disponibles',
    Fecha: '2026-03-21',
    Estado: 'Completada',
    Responsable: 'Admin',
  },
  {
    Codigo: 'ACT-003',
    Id: 'ACT-003',
    Codigo_oportunidad: 'OPP-002',
    Tipo: 'Reunión',
    Descripcion: 'Reunión presencial para presentar programa Business English',
    Fecha: '2026-03-15',
    Estado: 'Completada',
    Responsable: 'Director Académico',
  },
  {
    Codigo: 'ACT-004',
    Id: 'ACT-004',
    Codigo_oportunidad: 'OPP-002',
    Tipo: 'Email',
    Descripcion: 'Envío de cotización formal y plan de pago',
    Fecha: '2026-03-16',
    Estado: 'Completada',
    Responsable: 'Admin',
  },
  {
    Codigo: 'ACT-005',
    Id: 'ACT-005',
    Codigo_oportunidad: 'OPP-003',
    Tipo: 'Llamada',
    Descripcion: 'Primera llamada — consulta sobre preparación TOEFL',
    Fecha: '2026-03-06',
    Estado: 'Completada',
    Responsable: 'Admin',
  },
  {
    Codigo: 'ACT-006',
    Id: 'ACT-006',
    Codigo_oportunidad: 'OPP-003',
    Tipo: 'Tarea',
    Descripcion: 'Agendar examen de ubicación gratuito',
    Fecha: '2026-03-25',
    Estado: 'Pendiente',
    Responsable: 'Admin',
  },
];

module.exports = {
  programas,
  periodos,
  sedes,
  contactos,
  estudiantes,
  oportunidades,
  ordenesDePago,
  conceptosDePago,
  matriculas,
  inscripciones,
  estadocuentaestudiantes,
  pagosPendientes,
  pagos,
  negocios,
  actividades,
};
